/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export function defineContractComponents(world: World) {
  return {
	  Secret: (() => {
	    return defineComponent(
	      world,
	      { owner: RecsType.BigInt, value: RecsType.Number },
	      {
	        metadata: {
	          name: "Secret",
	          types: ["contractaddress","u8"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
  };
}
